site_name: Apuntes de Tzinm
site_description: Apuntes sobre lo que voy aprendiendo
site_author: Tzinm

repo_name: tzinm/mis-apuntes
repo_url: https://github.com/tzinm/mis-apuntes

copyright: Copyright &copy; 2020 Tzinm

edit_uri: ''

theme:
  name: material
  custom_dir: personalizaciones
  language: es
  palette:
    scheme: preference
    primary: brown
    accent: blue-grey
  font:
    text: PT Sans
    code: PT Sans Mono
  icon:
#    logo: octicons/book
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
  favicon: Imagenes/v-de-venganza.png

markdown_extensions:
  - admonition
  - codehilite:
     linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
      permalink: "#"
  - pymdownx.betterem:
      smart_enable: all
  - def_list
  - pymdownx.highlight:
      linenums: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - personalizaciones/.icons
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tilde

plugins:
  - search:
      lang:
        - es
#  - git-revision-date-localized

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tzinm
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/tzinm
    - icon: fontawesome/brands/telegram
      link: https://t.me/tzinm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tzinm1

nav:
 - Home: index.md
 - Docker:
     - Introducción a Docker: ./Docker/introduccion-docker.md
     - Imágenes: ./Docker/imagenes-docker.md
     - Contenedores: ./Docker/contenedores-docker.md
     - Volúmenes: ./Docker/volumenes-docker.md
     - Redes: ./Docker/redes-docker.md
     - Docker Compose: ./Docker/docker-compose.md
     - Seguridad: ./Docker/seguridad-docker.md
     - Información adicional: ./Docker/informacion-adicional.md
     - Contenedores de ejemplo: ./Docker/Contenedores.md
     - Referencias: ./Docker/referencias.md
 - Kubernetes:
     - Introducción a Kubernetes: ./Kubernetes/introduccion-kubernetes.md
     - Kubectl: ./Kubernetes/kubectl.md
     - Kubernetes en Raspberry Pi: ./Kubernetes/kubernetes-raspberrypi.md
     - Referencias: ./Kubernetes/referencias.md
 - Git:
     - Introducción a Git: ./Git/introduccion-git.md
     - Configuración inicial: ./Git/configuracion-inicial.md
     - Comandos genéricos: ./Git/comandos-git.md
     - Ramas: ./Git/ramas.md
     - Tags: ./Git/git-tags.md
     - Hosting para git: ./Git/git-hosting.md
     - Bare Repositories: ./Git/bare-repositories.md
     - Información adicional: ./Git/informacion-adicional.md
     - Referencias: ./Git/referencias.md
 - OpenMediaVault:
     - Políticas de actualizaciones: ./OpenMediaVault/Politica-actualizaciones.md
     - Logical Volume Management: ./OpenMediaVault/LVM.md
     - Rclone in OMV: ./OpenMediaVault/Rclone.md
 - MacOS:
     - Terminal: ./MacOS/personalizando-terminal.md
 - Router Asus:
     - Configurando DuckDNS: ./Asus/Custom-DDNS.md
