site_name: Documentacion
site_description: Apuntes sobre lo que voy aprendiendo
site_author: Tzinm

repo_name: tzinm/mis-apuntes
repo_url: https://github.com/tzinm/mis-apuntes

copyright: Copyright &copy; 2020 Tzinm

edit_uri: ''

theme:
  name: material
  language: es
  palette:
    primary: amber
    accent: brown
  font:
    text: PT Sans
    code: PT Sans Mono
  icon:
    logo: octicons/book
    repo: fontawesome/brands/github
  features:
    - tabs
    - instant
  favicon: assets/images/favicon.png

markdown_extensions:
  - admonition
  - codehilite:
     linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
      permalink: "#"
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tilde

plugins:
  - search:
      lang:
        - es
#  - git-revision-date-localized

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tzinm
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/tzinm
    - icon: fontawesome/brands/telegram
      link: https://t.me/tzinm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tzinm1

nav:
 - Home: index.md
 - Docker:
     - Conociendo Docker: ./Docker/Docker.md
     - Contenedores de ejemplo: ./Docker/Contenedores.md
 - OpenMediaVault:
     - Políticas de actualizaciones: ./OpenMediaVault/Politica-actualizaciones.md
     - Logical Volume Management: ./OpenMediaVault/LVM.md
     - Rclone in OMV: ./OpenMediaVault/Rclone.md
 - MacOS:
     - Terminal: ./MacOS/personalizando-terminal.md
 - Router Asus:
     - Configurando DuckDNS: ./Asus/Custom-DDNS.md
